version: "3.7"
services:
  db:
    image: postgres:11.7-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0.8-alpine
    ports:
      - "6379:6379"
  test:
    build:
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
      context: .
      dockerfile: ./container/test/Dockerfile
    links:
      - "db:database"
      - "redis:redis"
  lint:
    build:
      context: .
      dockerfile: ./container/lint/Dockerfile
  build:
    build:
      context: .
      dockerfile: ./container/build/Dockerfile
